
language: r
cache: packages
sudo: required

compiler:
  - gcc
  - clang
  
#change when submitting 
warnings_are_errors: false

# R versions to be tested on
r: 
  - bioc-release
  - bioc-devel

bioc_required: true
bioc_use_devel: true

r_github_packages:
  - hadley/devtools
  - r-lib/covr

r_packages:
#  - RCurl
  - covr
  - Rcpp
  - DT
  - shiny 
  - methods 
  - graphics
  - shinyBS
  - cli
  - rlang

bioc_packages:
  - IRanges
  - Biostrings 
  - ShortRead
  - S4Vectors
  - BiocCheck

os:
- linux
dist: trusty

r_build_args: '--no-build-vignettes --no-manual'
r_check_args: '--no-vignettes --no-manual --no-resave-data --as-cran --timings'
r_check_time: 'TRUE'
r_check_tests: 'TRUE'
r_check_timings: '0'

env:
  global:
   - CRAN: http://cran.rstudio.com

matrix:
  include:
    - os: osx
#    - os: osx
#      osx_image: xcode6.4
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode8.1
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9.1
    - os: osx
      osx_image: xcode9.3beta

before_install:
# solve mongo db expired key problem
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6 && sudo apt-get update; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install r-base-dev && sudo apt-get install binutils && sudo apt-get install gcc; fi;
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libssl-dev && sudo apt-get install libcurl4-openssl-dev && sudo apt-get install libxml2-dev; fi;
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install r-cran-rcurl && sudo apt-get install r-cran-xml; fi;
 - Rscript -e 'source("https://gist.githubusercontent.com/leandroroser/c9f8169cc842bd62b8792cc547edb903/raw/c8befc51f61d6c7e740d8c691c41a8f8dc7a177c/test_FastqCleaner_dependences.R")'

#- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get stable; fi
# - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo brew update; fi;

after_install:
- echo 'session info: ----> '
- Rscript -e 'sessionInfo()'

after_success:
- Rscript -e 'covr::codecov()'
- R CMD INSTALL *tar.gz --no-build-vignettes --no-manual
- R CMD BiocCheck
- echo "Session info:"
- echo $(Rscript -e "library(FastqCleaner); sessionInfo()")

notifications:
  email:
    on_success: change
    on_failure: change
